// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A Swahili voice-to-text search AI agent.
 *
 * - swahiliVoiceSearch - A function that handles the Swahili voice search process.
 * - SwahiliVoiceSearchInput - The input type for the swahiliVoiceSearch function.
 * - SwahiliVoiceSearchOutput - The return type for the swahiliVoiceSearch function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SwahiliVoiceSearchInputSchema = z.object({
  voiceInput: z
    .string()
    .describe('The Swahili voice input to be converted to text.'),
});
export type SwahiliVoiceSearchInput = z.infer<typeof SwahiliVoiceSearchInputSchema>;

const SwahiliVoiceSearchOutputSchema = z.object({
  searchText: z
    .string()
    .describe('The converted English text from the Swahili voice input.'),
});
export type SwahiliVoiceSearchOutput = z.infer<typeof SwahiliVoiceSearchOutputSchema>;

export async function swahiliVoiceSearch(input: SwahiliVoiceSearchInput): Promise<SwahiliVoiceSearchOutput> {
  return swahiliVoiceSearchFlow(input);
}

const prompt = ai.definePrompt({
  name: 'swahiliVoiceSearchPrompt',
  input: {schema: SwahiliVoiceSearchInputSchema},
  output: {schema: SwahiliVoiceSearchOutputSchema},
  prompt: `You are a helpful assistant that converts Swahili voice input to English text for searching produce.

Convert the following Swahili voice input to English text:

Swahili Voice Input: {{{voiceInput}}}`,
});

const swahiliVoiceSearchFlow = ai.defineFlow(
  {
    name: 'swahiliVoiceSearchFlow',
    inputSchema: SwahiliVoiceSearchInputSchema,
    outputSchema: SwahiliVoiceSearchOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
